import csv
import pandas
import os

files=os.listdir('C:\\CJQ_DATA')
for i in files:
    if 'dut' in i: 
        test2=i.split('_')[2]
        files_2=os.listdir('C:\\CJQ_DATA\\'+test2)

        L2R6DWPD={'Read_BW':[],'Write_BW':[],'P99_Read_Latency':[],'P99.99_Read_Latency':[],'P99.9999_Read_Latency':[],'Max_Read_Latency':[],'P99.99_Write_Latency':[],'P99.9999_Write_Latency':[],'Max_Write_Latency':[]}
        L2R9DWPD={'Read_BW':[],'Write_BW':[],'P99_Read_Latency':[],'P99.99_Read_Latency':[],'P99.9999_Read_Latency':[],'Max_Read_Latency':[],'P99.99_Write_Latency':[],'P99.9999_Write_Latency':[],'Max_Write_Latency':[]}
        MyRocks_Heavy_wTRIM={'Read_BW':[],'Write_BW':[],'P99_Read_Latency':[],'P99.99_Read_Latency':[],'P99.9999_Read_Latency':[],'Max_Read_Latency':[],'P99.99_Write_Latency':[],'P99.9999_Write_Latency':[],'Max_Write_Latency':[]}
        FLeaf_wTRIM={'Read_BW':[],'Write_BW':[],'P99_Read_Latency':[],'P99.99_Read_Latency':[],'P99.9999_Read_Latency':[],'Max_Read_Latency':[],'P99.99_Write_Latency':[],'P99.9999_Write_Latency':[],'Max_Write_Latency':[]}
        Msg_Migration_HQD_wTRIM={'Read_BW':[],'Write_BW':[],'P99_Read_Latency':[],'P99.99_Read_Latency':[],'P99.9999_Read_Latency':[],'Max_Read_Latency':[],'P99.99_Write_Latency':[],'P99.9999_Write_Latency':[],'Max_Write_Latency':[]}
        M2R5DWPD={'Read_BW':[],'Write_BW':[],'P99_Read_Latency':[],'P99.99_Read_Latency':[],'P99.9999_Read_Latency':[],'Max_Read_Latency':[],'P99.99_Write_Latency':[],'P99.9999_Write_Latency':[],'Max_Write_Latency':[]}
        L2R1DWPD={'Read_BW':[],'Write_BW':[],'P99_Read_Latency':[],'P99.99_Read_Latency':[],'P99.9999_Read_Latency':[],'Max_Read_Latency':[],'P99.99_Write_Latency':[],'P99.9999_Write_Latency':[],'Max_Write_Latency':[]}
        SearchIndex_wTRIM={'Read_BW':[],'Write_BW':[],'P99_Read_Latency':[],'P99.99_Read_Latency':[],'P99.9999_Read_Latency':[],'Max_Read_Latency':[],'P99.99_Write_Latency':[],'P99.9999_Write_Latency':[],'Max_Write_Latency':[]}
        SearchLM_wTRIM={'Read_BW':[],'Write_BW':[],'P99_Read_Latency':[],'P99.99_Read_Latency':[],'P99.9999_Read_Latency':[],'Max_Read_Latency':[],'P99.99_Write_Latency':[],'P99.9999_Write_Latency':[],'Max_Write_Latency':[]}
        B_Cache={'Read_BW':[],'Write_BW':[],'P99_Read_Latency':[],'P99.99_Read_Latency':[],'P99.9999_Read_Latency':[],'Max_Read_Latency':[],'P99.99_Write_Latency':[],'P99.9999_Write_Latency':[],'Max_Write_Latency':[]}
        for ns in files_2:
            test3=ns.split('_')[3]
            dut=ns.split('_')[5]
            test2=ns.split('_')[4]
            csv=pandas.read_csv('C:\\CJQ_DATA\\'+test2+'\\Workload_Loop_Stress_'+test3+'_'+test2+'_'+dut)
            list1=['Read_BW','Write_BW','P99_Read_Latency','P99.99_Read_Latency','P99.9999_Read_Latency','Max_Read_Latency','P99.99_Write_Latency','P99.9999_Write_Latency','Max_Write_Latency']
            for i in list1:
                L2R6DWPD[i].append(csv[i][0])
                L2R9DWPD[i].append(csv[i][1])
                MyRocks_Heavy_wTRIM[i].append(csv[i][2])
                FLeaf_wTRIM[i].append(csv[i][3])
                Msg_Migration_HQD_wTRIM[i].append(csv[i][4])
                M2R5DWPD[i].append(csv[i][5])
                L2R1DWPD[i].append(csv[i][6])
                SearchIndex_wTRIM[i].append(csv[i][7])
                SearchLM_wTRIM[i].append(csv[i][8])
                B_Cache[i].append(csv[i][9])

        L2R6DWPD_sum={'Read_BW':{'MEDIAN':sum(L2R6DWPD['Read_BW'])/len(L2R6DWPD['Read_BW']),'MAX':max(L2R6DWPD['Read_BW']),'MIN':min(L2R6DWPD['Read_BW'])},'Write_BW':{'MEDIAN':sum(L2R6DWPD['Write_BW'])/len(L2R6DWPD['Write_BW']),'MAX':max(L2R6DWPD['Write_BW']),'MIN':min(L2R6DWPD['Write_BW'])},'P99_Read_Latency':{'MEDIAN':sum(L2R6DWPD['P99_Read_Latency'])/len(L2R6DWPD['P99_Read_Latency']),'MAX':max(L2R6DWPD['P99_Read_Latency']),'MIN':min(L2R6DWPD['P99_Read_Latency'])},'P99.99_Read_Latency':{'MEDIAN':sum(L2R6DWPD['P99.99_Read_Latency'])/len(L2R6DWPD['P99.99_Read_Latency']),'MAX':max(L2R6DWPD['P99.99_Read_Latency']),'MIN':min(L2R6DWPD['P99.99_Read_Latency'])},'P99.9999_Read_Latency':{'MEDIAN':sum(L2R6DWPD['P99.9999_Read_Latency'])/len(L2R6DWPD['P99.9999_Read_Latency']),'MAX':max(L2R6DWPD['P99.9999_Read_Latency']),'MIN':min(L2R6DWPD['P99.9999_Read_Latency'])},'Max_Read_Latency':{'MEDIAN':sum(L2R6DWPD['Max_Read_Latency'])/len(L2R6DWPD['Max_Read_Latency']),'MAX':max(L2R6DWPD['Max_Read_Latency']),'MIN':min(L2R6DWPD['Max_Read_Latency'])},'P99.99_Write_Latency':{'MEDIAN':sum(L2R6DWPD['P99.99_Write_Latency'])/len(L2R6DWPD['P99.99_Write_Latency']),'MAX':max(L2R6DWPD['P99.99_Write_Latency']),'MIN':min(L2R6DWPD['P99.99_Write_Latency'])},'P99.9999_Write_Latency':{'MEDIAN':sum(L2R6DWPD['P99.9999_Write_Latency'])/len(L2R6DWPD['P99.9999_Write_Latency']),'MAX':max(L2R6DWPD['P99.9999_Write_Latency']),'MIN':min(L2R6DWPD['P99.9999_Write_Latency'])},'Max_Write_Latency':{'MEDIAN':sum(L2R6DWPD['Max_Write_Latency'])/len(L2R6DWPD['Max_Write_Latency']),'MAX':max(L2R6DWPD['Max_Write_Latency']),'MIN':min(L2R6DWPD['Max_Write_Latency'])}}
        df=pandas.DataFrame(L2R6DWPD_sum)

        L2R9DWPD_sum={'Read_BW':{'MEDIAN':sum(L2R9DWPD['Read_BW'])/len(L2R9DWPD['Read_BW']),'MAX':max(L2R9DWPD['Read_BW']),'MIN':min(L2R9DWPD['Read_BW'])},'Write_BW':{'MEDIAN':sum(L2R9DWPD['Write_BW'])/len(L2R9DWPD['Write_BW']),'MAX':max(L2R9DWPD['Write_BW']),'MIN':min(L2R9DWPD['Write_BW'])},'P99_Read_Latency':{'MEDIAN':sum(L2R9DWPD['P99_Read_Latency'])/len(L2R9DWPD['P99_Read_Latency']),'MAX':max(L2R9DWPD['P99_Read_Latency']),'MIN':min(L2R9DWPD['P99_Read_Latency'])},'P99.99_Read_Latency':{'MEDIAN':sum(L2R9DWPD['P99.99_Read_Latency'])/len(L2R9DWPD['P99.99_Read_Latency']),'MAX':max(L2R9DWPD['P99.99_Read_Latency']),'MIN':min(L2R9DWPD['P99.99_Read_Latency'])},'P99.9999_Read_Latency':{'MEDIAN':sum(L2R9DWPD['P99.9999_Read_Latency'])/len(L2R9DWPD['P99.9999_Read_Latency']),'MAX':max(L2R9DWPD['P99.9999_Read_Latency']),'MIN':min(L2R9DWPD['P99.9999_Read_Latency'])},'Max_Read_Latency':{'MEDIAN':sum(L2R9DWPD['Max_Read_Latency'])/len(L2R9DWPD['Max_Read_Latency']),'MAX':max(L2R9DWPD['Max_Read_Latency']),'MIN':min(L2R9DWPD['Max_Read_Latency'])},'P99.99_Write_Latency':{'MEDIAN':sum(L2R9DWPD['P99.99_Write_Latency'])/len(L2R9DWPD['P99.99_Write_Latency']),'MAX':max(L2R9DWPD['P99.99_Write_Latency']),'MIN':min(L2R9DWPD['P99.99_Write_Latency'])},'P99.9999_Write_Latency':{'MEDIAN':sum(L2R9DWPD['P99.9999_Write_Latency'])/len(L2R9DWPD['P99.9999_Write_Latency']),'MAX':max(L2R9DWPD['P99.9999_Write_Latency']),'MIN':min(L2R9DWPD['P99.9999_Write_Latency'])},'Max_Write_Latency':{'MEDIAN':sum(L2R9DWPD['Max_Write_Latency'])/len(L2R9DWPD['Max_Write_Latency']),'MAX':max(L2R9DWPD['Max_Write_Latency']),'MIN':min(L2R9DWPD['Max_Write_Latency'])}}
        df1=pandas.DataFrame(L2R9DWPD_sum)

        MyRocks_Heavy_wTRIM_sum={'Read_BW':{'MEDIAN':sum(MyRocks_Heavy_wTRIM['Read_BW'])/len(MyRocks_Heavy_wTRIM['Read_BW']),'MAX':max(MyRocks_Heavy_wTRIM['Read_BW']),'MIN':min(MyRocks_Heavy_wTRIM['Read_BW'])},'Write_BW':{'MEDIAN':sum(MyRocks_Heavy_wTRIM['Write_BW'])/len(MyRocks_Heavy_wTRIM['Write_BW']),'MAX':max(MyRocks_Heavy_wTRIM['Write_BW']),'MIN':min(MyRocks_Heavy_wTRIM['Write_BW'])},'P99_Read_Latency':{'MEDIAN':sum(MyRocks_Heavy_wTRIM['P99_Read_Latency'])/len(MyRocks_Heavy_wTRIM['P99_Read_Latency']),'MAX':max(MyRocks_Heavy_wTRIM['P99_Read_Latency']),'MIN':min(MyRocks_Heavy_wTRIM['P99_Read_Latency'])},'P99.99_Read_Latency':{'MEDIAN':sum(MyRocks_Heavy_wTRIM['P99.99_Read_Latency'])/len(MyRocks_Heavy_wTRIM['P99.99_Read_Latency']),'MAX':max(MyRocks_Heavy_wTRIM['P99.99_Read_Latency']),'MIN':min(MyRocks_Heavy_wTRIM['P99.99_Read_Latency'])},'P99.9999_Read_Latency':{'MEDIAN':sum(MyRocks_Heavy_wTRIM['P99.9999_Read_Latency'])/len(MyRocks_Heavy_wTRIM['P99.9999_Read_Latency']),'MAX':max(MyRocks_Heavy_wTRIM['P99.9999_Read_Latency']),'MIN':min(MyRocks_Heavy_wTRIM['P99.9999_Read_Latency'])},'Max_Read_Latency':{'MEDIAN':sum(MyRocks_Heavy_wTRIM['Max_Read_Latency'])/len(MyRocks_Heavy_wTRIM['Max_Read_Latency']),'MAX':max(MyRocks_Heavy_wTRIM['Max_Read_Latency']),'MIN':min(MyRocks_Heavy_wTRIM['Max_Read_Latency'])},'P99.99_Write_Latency':{'MEDIAN':sum(MyRocks_Heavy_wTRIM['P99.99_Write_Latency'])/len(MyRocks_Heavy_wTRIM['P99.99_Write_Latency']),'MAX':max(MyRocks_Heavy_wTRIM['P99.99_Write_Latency']),'MIN':min(MyRocks_Heavy_wTRIM['P99.99_Write_Latency'])},'P99.9999_Write_Latency':{'MEDIAN':sum(MyRocks_Heavy_wTRIM['P99.9999_Write_Latency'])/len(MyRocks_Heavy_wTRIM['P99.9999_Write_Latency']),'MAX':max(MyRocks_Heavy_wTRIM['P99.9999_Write_Latency']),'MIN':min(MyRocks_Heavy_wTRIM['P99.9999_Write_Latency'])},'Max_Write_Latency':{'MEDIAN':sum(MyRocks_Heavy_wTRIM['Max_Write_Latency'])/len(MyRocks_Heavy_wTRIM['Max_Write_Latency']),'MAX':max(MyRocks_Heavy_wTRIM['Max_Write_Latency']),'MIN':min(MyRocks_Heavy_wTRIM['Max_Write_Latency'])}}
        df2=pandas.DataFrame(MyRocks_Heavy_wTRIM_sum)

        FLeaf_wTRIM_sum={'Read_BW':{'MEDIAN':sum(FLeaf_wTRIM['Read_BW'])/len(FLeaf_wTRIM['Read_BW']),'MAX':max(FLeaf_wTRIM['Read_BW']),'MIN':min(FLeaf_wTRIM['Read_BW'])},'Write_BW':{'MEDIAN':sum(FLeaf_wTRIM['Write_BW'])/len(FLeaf_wTRIM['Write_BW']),'MAX':max(FLeaf_wTRIM['Write_BW']),'MIN':min(FLeaf_wTRIM['Write_BW'])},'P99_Read_Latency':{'MEDIAN':sum(FLeaf_wTRIM['P99_Read_Latency'])/len(FLeaf_wTRIM['P99_Read_Latency']),'MAX':max(FLeaf_wTRIM['P99_Read_Latency']),'MIN':min(FLeaf_wTRIM['P99_Read_Latency'])},'P99.99_Read_Latency':{'MEDIAN':sum(FLeaf_wTRIM['P99.99_Read_Latency'])/len(FLeaf_wTRIM['P99.99_Read_Latency']),'MAX':max(FLeaf_wTRIM['P99.99_Read_Latency']),'MIN':min(FLeaf_wTRIM['P99.99_Read_Latency'])},'P99.9999_Read_Latency':{'MEDIAN':sum(FLeaf_wTRIM['P99.9999_Read_Latency'])/len(FLeaf_wTRIM['P99.9999_Read_Latency']),'MAX':max(FLeaf_wTRIM['P99.9999_Read_Latency']),'MIN':min(FLeaf_wTRIM['P99.9999_Read_Latency'])},'Max_Read_Latency':{'MEDIAN':sum(FLeaf_wTRIM['Max_Read_Latency'])/len(FLeaf_wTRIM['Max_Read_Latency']),'MAX':max(FLeaf_wTRIM['Max_Read_Latency']),'MIN':min(FLeaf_wTRIM['Max_Read_Latency'])},'P99.99_Write_Latency':{'MEDIAN':sum(FLeaf_wTRIM['P99.99_Write_Latency'])/len(FLeaf_wTRIM['P99.99_Write_Latency']),'MAX':max(FLeaf_wTRIM['P99.99_Write_Latency']),'MIN':min(FLeaf_wTRIM['P99.99_Write_Latency'])},'P99.9999_Write_Latency':{'MEDIAN':sum(FLeaf_wTRIM['P99.9999_Write_Latency'])/len(FLeaf_wTRIM['P99.9999_Write_Latency']),'MAX':max(FLeaf_wTRIM['P99.9999_Write_Latency']),'MIN':min(FLeaf_wTRIM['P99.9999_Write_Latency'])},'Max_Write_Latency':{'MEDIAN':sum(FLeaf_wTRIM['Max_Write_Latency'])/len(FLeaf_wTRIM['Max_Write_Latency']),'MAX':max(FLeaf_wTRIM['Max_Write_Latency']),'MIN':min(FLeaf_wTRIM['Max_Write_Latency'])}}
        df3=pandas.DataFrame(FLeaf_wTRIM_sum)

        Msg_Migration_HQD_wTRIM_sum={'Read_BW':{'MEDIAN':sum(Msg_Migration_HQD_wTRIM['Read_BW'])/len(Msg_Migration_HQD_wTRIM['Read_BW']),'MAX':max(Msg_Migration_HQD_wTRIM['Read_BW']),'MIN':min(Msg_Migration_HQD_wTRIM['Read_BW'])},'Write_BW':{'MEDIAN':sum(Msg_Migration_HQD_wTRIM['Write_BW'])/len(Msg_Migration_HQD_wTRIM['Write_BW']),'MAX':max(Msg_Migration_HQD_wTRIM['Write_BW']),'MIN':min(Msg_Migration_HQD_wTRIM['Write_BW'])},'P99_Read_Latency':{'MEDIAN':sum(Msg_Migration_HQD_wTRIM['P99_Read_Latency'])/len(Msg_Migration_HQD_wTRIM['P99_Read_Latency']),'MAX':max(Msg_Migration_HQD_wTRIM['P99_Read_Latency']),'MIN':min(Msg_Migration_HQD_wTRIM['P99_Read_Latency'])},'P99.99_Read_Latency':{'MEDIAN':sum(Msg_Migration_HQD_wTRIM['P99.99_Read_Latency'])/len(Msg_Migration_HQD_wTRIM['P99.99_Read_Latency']),'MAX':max(Msg_Migration_HQD_wTRIM['P99.99_Read_Latency']),'MIN':min(Msg_Migration_HQD_wTRIM['P99.99_Read_Latency'])},'P99.9999_Read_Latency':{'MEDIAN':sum(Msg_Migration_HQD_wTRIM['P99.9999_Read_Latency'])/len(Msg_Migration_HQD_wTRIM['P99.9999_Read_Latency']),'MAX':max(Msg_Migration_HQD_wTRIM['P99.9999_Read_Latency']),'MIN':min(Msg_Migration_HQD_wTRIM['P99.9999_Read_Latency'])},'Max_Read_Latency':{'MEDIAN':sum(Msg_Migration_HQD_wTRIM['Max_Read_Latency'])/len(Msg_Migration_HQD_wTRIM['Max_Read_Latency']),'MAX':max(Msg_Migration_HQD_wTRIM['Max_Read_Latency']),'MIN':min(Msg_Migration_HQD_wTRIM['Max_Read_Latency'])},'P99.99_Write_Latency':{'MEDIAN':sum(Msg_Migration_HQD_wTRIM['P99.99_Write_Latency'])/len(Msg_Migration_HQD_wTRIM['P99.99_Write_Latency']),'MAX':max(Msg_Migration_HQD_wTRIM['P99.99_Write_Latency']),'MIN':min(Msg_Migration_HQD_wTRIM['P99.99_Write_Latency'])},'P99.9999_Write_Latency':{'MEDIAN':sum(Msg_Migration_HQD_wTRIM['P99.9999_Write_Latency'])/len(Msg_Migration_HQD_wTRIM['P99.9999_Write_Latency']),'MAX':max(Msg_Migration_HQD_wTRIM['P99.9999_Write_Latency']),'MIN':min(Msg_Migration_HQD_wTRIM['P99.9999_Write_Latency'])},'Max_Write_Latency':{'MEDIAN':sum(Msg_Migration_HQD_wTRIM['Max_Write_Latency'])/len(Msg_Migration_HQD_wTRIM['Max_Write_Latency']),'MAX':max(Msg_Migration_HQD_wTRIM['Max_Write_Latency']),'MIN':min(Msg_Migration_HQD_wTRIM['Max_Write_Latency'])}}
        df4=pandas.DataFrame(Msg_Migration_HQD_wTRIM_sum)

        M2R5DWPD_sum={'Read_BW':{'MEDIAN':sum(M2R5DWPD['Read_BW'])/len(M2R5DWPD['Read_BW']),'MAX':max(M2R5DWPD['Read_BW']),'MIN':min(M2R5DWPD['Read_BW'])},'Write_BW':{'MEDIAN':sum(M2R5DWPD['Write_BW'])/len(M2R5DWPD['Write_BW']),'MAX':max(M2R5DWPD['Write_BW']),'MIN':min(M2R5DWPD['Write_BW'])},'P99_Read_Latency':{'MEDIAN':sum(M2R5DWPD['P99_Read_Latency'])/len(M2R5DWPD['P99_Read_Latency']),'MAX':max(M2R5DWPD['P99_Read_Latency']),'MIN':min(M2R5DWPD['P99_Read_Latency'])},'P99.99_Read_Latency':{'MEDIAN':sum(M2R5DWPD['P99.99_Read_Latency'])/len(M2R5DWPD['P99.99_Read_Latency']),'MAX':max(M2R5DWPD['P99.99_Read_Latency']),'MIN':min(M2R5DWPD['P99.99_Read_Latency'])},'P99.9999_Read_Latency':{'MEDIAN':sum(M2R5DWPD['P99.9999_Read_Latency'])/len(M2R5DWPD['P99.9999_Read_Latency']),'MAX':max(M2R5DWPD['P99.9999_Read_Latency']),'MIN':min(M2R5DWPD['P99.9999_Read_Latency'])},'Max_Read_Latency':{'MEDIAN':sum(M2R5DWPD['Max_Read_Latency'])/len(M2R5DWPD['Max_Read_Latency']),'MAX':max(M2R5DWPD['Max_Read_Latency']),'MIN':min(M2R5DWPD['Max_Read_Latency'])},'P99.99_Write_Latency':{'MEDIAN':sum(M2R5DWPD['P99.99_Write_Latency'])/len(M2R5DWPD['P99.99_Write_Latency']),'MAX':max(M2R5DWPD['P99.99_Write_Latency']),'MIN':min(M2R5DWPD['P99.99_Write_Latency'])},'P99.9999_Write_Latency':{'MEDIAN':sum(M2R5DWPD['P99.9999_Write_Latency'])/len(M2R5DWPD['P99.9999_Write_Latency']),'MAX':max(M2R5DWPD['P99.9999_Write_Latency']),'MIN':min(M2R5DWPD['P99.9999_Write_Latency'])},'Max_Write_Latency':{'MEDIAN':sum(M2R5DWPD['Max_Write_Latency'])/len(M2R5DWPD['Max_Write_Latency']),'MAX':max(M2R5DWPD['Max_Write_Latency']),'MIN':min(M2R5DWPD['Max_Write_Latency'])}}
        df5=pandas.DataFrame(M2R5DWPD_sum)

        L2R1DWPD_sum={'Read_BW':{'MEDIAN':sum(L2R1DWPD['Read_BW'])/len(L2R1DWPD['Read_BW']),'MAX':max(L2R1DWPD['Read_BW']),'MIN':min(L2R1DWPD['Read_BW'])},'Write_BW':{'MEDIAN':sum(L2R1DWPD['Write_BW'])/len(L2R1DWPD['Write_BW']),'MAX':max(L2R1DWPD['Write_BW']),'MIN':min(L2R1DWPD['Write_BW'])},'P99_Read_Latency':{'MEDIAN':sum(L2R1DWPD['P99_Read_Latency'])/len(L2R1DWPD['P99_Read_Latency']),'MAX':max(L2R1DWPD['P99_Read_Latency']),'MIN':min(L2R1DWPD['P99_Read_Latency'])},'P99.99_Read_Latency':{'MEDIAN':sum(L2R1DWPD['P99.99_Read_Latency'])/len(L2R1DWPD['P99.99_Read_Latency']),'MAX':max(L2R1DWPD['P99.99_Read_Latency']),'MIN':min(L2R1DWPD['P99.99_Read_Latency'])},'P99.9999_Read_Latency':{'MEDIAN':sum(L2R1DWPD['P99.9999_Read_Latency'])/len(L2R1DWPD['P99.9999_Read_Latency']),'MAX':max(L2R1DWPD['P99.9999_Read_Latency']),'MIN':min(L2R1DWPD['P99.9999_Read_Latency'])},'Max_Read_Latency':{'MEDIAN':sum(L2R1DWPD['Max_Read_Latency'])/len(L2R1DWPD['Max_Read_Latency']),'MAX':max(L2R1DWPD['Max_Read_Latency']),'MIN':min(L2R1DWPD['Max_Read_Latency'])},'P99.99_Write_Latency':{'MEDIAN':sum(L2R1DWPD['P99.99_Write_Latency'])/len(L2R1DWPD['P99.99_Write_Latency']),'MAX':max(L2R1DWPD['P99.99_Write_Latency']),'MIN':min(L2R1DWPD['P99.99_Write_Latency'])},'P99.9999_Write_Latency':{'MEDIAN':sum(L2R1DWPD['P99.9999_Write_Latency'])/len(L2R1DWPD['P99.9999_Write_Latency']),'MAX':max(L2R1DWPD['P99.9999_Write_Latency']),'MIN':min(L2R1DWPD['P99.9999_Write_Latency'])},'Max_Write_Latency':{'MEDIAN':sum(L2R1DWPD['Max_Write_Latency'])/len(L2R1DWPD['Max_Write_Latency']),'MAX':max(L2R1DWPD['Max_Write_Latency']),'MIN':min(L2R1DWPD['Max_Write_Latency'])}}
        df6=pandas.DataFrame(L2R1DWPD_sum)

        SearchIndex_wTRIM_sum={'Read_BW':{'MEDIAN':sum(SearchIndex_wTRIM['Read_BW'])/len(SearchIndex_wTRIM['Read_BW']),'MAX':max(SearchIndex_wTRIM['Read_BW']),'MIN':min(SearchIndex_wTRIM['Read_BW'])},'Write_BW':{'MEDIAN':sum(SearchIndex_wTRIM['Write_BW'])/len(SearchIndex_wTRIM['Write_BW']),'MAX':max(SearchIndex_wTRIM['Write_BW']),'MIN':min(SearchIndex_wTRIM['Write_BW'])},'P99_Read_Latency':{'MEDIAN':sum(SearchIndex_wTRIM['P99_Read_Latency'])/len(SearchIndex_wTRIM['P99_Read_Latency']),'MAX':max(SearchIndex_wTRIM['P99_Read_Latency']),'MIN':min(SearchIndex_wTRIM['P99_Read_Latency'])},'P99.99_Read_Latency':{'MEDIAN':sum(SearchIndex_wTRIM['P99.99_Read_Latency'])/len(SearchIndex_wTRIM['P99.99_Read_Latency']),'MAX':max(SearchIndex_wTRIM['P99.99_Read_Latency']),'MIN':min(SearchIndex_wTRIM['P99.99_Read_Latency'])},'P99.9999_Read_Latency':{'MEDIAN':sum(SearchIndex_wTRIM['P99.9999_Read_Latency'])/len(SearchIndex_wTRIM['P99.9999_Read_Latency']),'MAX':max(SearchIndex_wTRIM['P99.9999_Read_Latency']),'MIN':min(SearchIndex_wTRIM['P99.9999_Read_Latency'])},'Max_Read_Latency':{'MEDIAN':sum(SearchIndex_wTRIM['Max_Read_Latency'])/len(SearchIndex_wTRIM['Max_Read_Latency']),'MAX':max(SearchIndex_wTRIM['Max_Read_Latency']),'MIN':min(SearchIndex_wTRIM['Max_Read_Latency'])},'P99.99_Write_Latency':{'MEDIAN':sum(SearchIndex_wTRIM['P99.99_Write_Latency'])/len(SearchIndex_wTRIM['P99.99_Write_Latency']),'MAX':max(SearchIndex_wTRIM['P99.99_Write_Latency']),'MIN':min(SearchIndex_wTRIM['P99.99_Write_Latency'])},'P99.9999_Write_Latency':{'MEDIAN':sum(SearchIndex_wTRIM['P99.9999_Write_Latency'])/len(SearchIndex_wTRIM['P99.9999_Write_Latency']),'MAX':max(SearchIndex_wTRIM['P99.9999_Write_Latency']),'MIN':min(SearchIndex_wTRIM['P99.9999_Write_Latency'])},'Max_Write_Latency':{'MEDIAN':sum(SearchIndex_wTRIM['Max_Write_Latency'])/len(SearchIndex_wTRIM['Max_Write_Latency']),'MAX':max(SearchIndex_wTRIM['Max_Write_Latency']),'MIN':min(SearchIndex_wTRIM['Max_Write_Latency'])}}
        df7=pandas.DataFrame(SearchIndex_wTRIM_sum)

        SearchLM_wTRIM_sum={'Read_BW':{'MEDIAN':sum(SearchLM_wTRIM['Read_BW'])/len(SearchLM_wTRIM['Read_BW']),'MAX':max(SearchLM_wTRIM['Read_BW']),'MIN':min(SearchLM_wTRIM['Read_BW'])},'Write_BW':{'MEDIAN':sum(SearchLM_wTRIM['Write_BW'])/len(SearchLM_wTRIM['Write_BW']),'MAX':max(SearchLM_wTRIM['Write_BW']),'MIN':min(SearchLM_wTRIM['Write_BW'])},'P99_Read_Latency':{'MEDIAN':sum(SearchLM_wTRIM['P99_Read_Latency'])/len(SearchLM_wTRIM['P99_Read_Latency']),'MAX':max(SearchLM_wTRIM['P99_Read_Latency']),'MIN':min(SearchLM_wTRIM['P99_Read_Latency'])},'P99.99_Read_Latency':{'MEDIAN':sum(SearchLM_wTRIM['P99.99_Read_Latency'])/len(SearchLM_wTRIM['P99.99_Read_Latency']),'MAX':max(SearchLM_wTRIM['P99.99_Read_Latency']),'MIN':min(SearchLM_wTRIM['P99.99_Read_Latency'])},'P99.9999_Read_Latency':{'MEDIAN':sum(SearchLM_wTRIM['P99.9999_Read_Latency'])/len(SearchLM_wTRIM['P99.9999_Read_Latency']),'MAX':max(SearchLM_wTRIM['P99.9999_Read_Latency']),'MIN':min(SearchLM_wTRIM['P99.9999_Read_Latency'])},'Max_Read_Latency':{'MEDIAN':sum(SearchLM_wTRIM['Max_Read_Latency'])/len(SearchLM_wTRIM['Max_Read_Latency']),'MAX':max(SearchLM_wTRIM['Max_Read_Latency']),'MIN':min(SearchLM_wTRIM['Max_Read_Latency'])},'P99.99_Write_Latency':{'MEDIAN':sum(SearchLM_wTRIM['P99.99_Write_Latency'])/len(SearchLM_wTRIM['P99.99_Write_Latency']),'MAX':max(SearchLM_wTRIM['P99.99_Write_Latency']),'MIN':min(SearchLM_wTRIM['P99.99_Write_Latency'])},'P99.9999_Write_Latency':{'MEDIAN':sum(SearchLM_wTRIM['P99.9999_Write_Latency'])/len(SearchLM_wTRIM['P99.9999_Write_Latency']),'MAX':max(SearchLM_wTRIM['P99.9999_Write_Latency']),'MIN':min(SearchLM_wTRIM['P99.9999_Write_Latency'])},'Max_Write_Latency':{'MEDIAN':sum(SearchLM_wTRIM['Max_Write_Latency'])/len(SearchLM_wTRIM['Max_Write_Latency']),'MAX':max(SearchLM_wTRIM['Max_Write_Latency']),'MIN':min(SearchLM_wTRIM['Max_Write_Latency'])}}
        df8=pandas.DataFrame(SearchLM_wTRIM_sum)

        B_Cache_sum={'Read_BW':{'MEDIAN':sum(B_Cache['Read_BW'])/len(B_Cache['Read_BW']),'MAX':max(B_Cache['Read_BW']),'MIN':min(B_Cache['Read_BW'])},'Write_BW':{'MEDIAN':sum(B_Cache['Write_BW'])/len(B_Cache['Write_BW']),'MAX':max(B_Cache['Write_BW']),'MIN':min(B_Cache['Write_BW'])},'P99_Read_Latency':{'MEDIAN':sum(B_Cache['P99_Read_Latency'])/len(B_Cache['P99_Read_Latency']),'MAX':max(B_Cache['P99_Read_Latency']),'MIN':min(B_Cache['P99_Read_Latency'])},'P99.99_Read_Latency':{'MEDIAN':sum(B_Cache['P99.99_Read_Latency'])/len(B_Cache['P99.99_Read_Latency']),'MAX':max(B_Cache['P99.99_Read_Latency']),'MIN':min(B_Cache['P99.99_Read_Latency'])},'P99.9999_Read_Latency':{'MEDIAN':sum(B_Cache['P99.9999_Read_Latency'])/len(B_Cache['P99.9999_Read_Latency']),'MAX':max(B_Cache['P99.9999_Read_Latency']),'MIN':min(B_Cache['P99.9999_Read_Latency'])},'Max_Read_Latency':{'MEDIAN':sum(B_Cache['Max_Read_Latency'])/len(B_Cache['Max_Read_Latency']),'MAX':max(B_Cache['Max_Read_Latency']),'MIN':min(B_Cache['Max_Read_Latency'])},'P99.99_Write_Latency':{'MEDIAN':sum(B_Cache['P99.99_Write_Latency'])/len(B_Cache['P99.99_Write_Latency']),'MAX':max(B_Cache['P99.99_Write_Latency']),'MIN':min(B_Cache['P99.99_Write_Latency'])},'P99.9999_Write_Latency':{'MEDIAN':sum(B_Cache['P99.9999_Write_Latency'])/len(B_Cache['P99.9999_Write_Latency']),'MAX':max(B_Cache['P99.9999_Write_Latency']),'MIN':min(B_Cache['P99.9999_Write_Latency'])},'Max_Write_Latency':{'MEDIAN':sum(B_Cache['Max_Write_Latency'])/len(B_Cache['Max_Write_Latency']),'MAX':max(B_Cache['Max_Write_Latency']),'MIN':min(B_Cache['Max_Write_Latency'])}}
        df9=pandas.DataFrame(B_Cache_sum)

        result=pandas.concat([df,df1,df2,df3,df4,df5,df6,df7,df8,df9])
        #print(result)
        result['Workload']=['4K_L2R6DWPD_wTRIM_run1','4K_L2R6DWPD_wTRIM_run1','4K_L2R6DWPD_wTRIM_run1','4K_L2R9DWPD_wTRIM_run1','4K_L2R9DWPD_wTRIM_run1','4K_L2R9DWPD_wTRIM_run1','MyRocks_Heavy_wTRIM_run1','MyRocks_Heavy_wTRIM_run1','MyRocks_Heavy_wTRIM_run1','FLeaf_wTRIM_run1','FLeaf_wTRIM_run1','FLeaf_wTRIM_run1','Msg_Migration_HQD_wTRIM_run1','Msg_Migration_HQD_wTRIM_run1','Msg_Migration_HQD_wTRIM_run1','4K_M2R.5DWPD_run1','4K_M2R.5DWPD_run1','4K_M2R.5DWPD_run1','4K_L2R1DWPD_run1','4K_L2R1DWPD_run1','4K_L2R1DWPD_run1','SearchIndex_wTRIM_run1','SearchIndex_wTRIM_run1','SearchIndex_wTRIM_run1','SearchLM_wTRIM_run1','SearchLM_wTRIM_run1','SearchLM_wTRIM_run1','B_Cache_run1','B_Cache_run1','B_Cache_run1']
        result=result[['Workload','Read_BW','Write_BW','P99_Read_Latency','P99.99_Read_Latency','P99.9999_Read_Latency','Max_Read_Latency','P99.99_Write_Latency','P99.9999_Write_Latency','Max_Write_Latency']]
        result.to_csv('C:\\CJQ_DATA\\Summary_'+test2+'.csv')    
        result1=pandas.read_csv('C:\\CJQ_DATA\\Summary_'+test2+'.csv')
        